porscheinformatik/clarity-addons

src/clr-addons/notification/notification.scss
detail: if the message keys are specified in the following way:
"message first line \n message second line" the notification component should wrap correctly
=> [160153](164606) fix notifications to wrap the line also on page breaks

src/clr-addons/notification/notification.ts, src/clr-addons/notification/scheduler-utils.ts
This makes tests that wait for Angular to become stable not stuck when a
notification is open.
=> Run notification timers outside the angular zone

src/clr-addons/quick-list/quick-list.ts
when quicklist is optional, no options should be displayed
=> fix mandatory param on quick-list items

src/clr-addons/mobile.scss
+ the !importants are necessary because of the dynamic positioning of the signpost
=> Adapt signpost display change for display on smartphone

src/clr-addons/themes/phs/variables.color.scss
This fixes the color for the PHS theme for progress spinner, radio button group and probably other places.
=> fix: color for PHS theme in different places

src/clr-addons/components.clr-addons.scss
If the content of a label is written on a separate line than the closing tag of the label, ie.
```
<label>
text content of the label
</label>
```
then the newline after the text content is causing the asterisk for 'required' labels to line-break.
This change ensures the asterisk always stays on the same line as the last character of the label.
=> Forms: fix asterisk for required labels line-breaking

package-lock.json, package.json, src/clr-addons/components.clr-addons.scss, src/clr-addons/package.json, src/clr-addons/themes/phs/variables.color.scss
Required asterisks would lock onto the window when there is no parent with position: relative available. This hotfix makes sure there always is one.
=> Forms: fix asterisk for required labels when there is no relative parent available

src/clr-addons/history/history-pinned.html, src/clr-addons/history/history-pinned.ts, src/clr-addons/history/history.html, src/clr-addons/history/history.service.ts, src/clr-addons/history/history.ts, src/dev/src/app/app.component.html, src/dev/src/app/app.component.ts, src/dev/src/app/app.module.ts, src/dev/src/app/route-history.service.ts
- Pinned history should use default links (using href).
- History dropdown menu should have a configurable position with 'bottom-right' as the default
- Only display 3 entries of history
- Fix hideLast was of type "true"
=> fix(history): use links in pinned history, fix dropdown position

src/clr-addons/components.clr-addons.scss
This restores the default z-index of dropdown menus so that it will show in front of the content panel.
Closes #852
=> Fix command bar dropdown menus z-index

package-lock.json, package.json, src/clr-addons/history/history.service.ts
* max url size for adding an entry to history = 256 characters
* max cookie content size = 1024 characters
=> add size constraints to clr.history coockie handling

package-lock.json, package.json, src/clr-addons/history/history.service.ts, src/clr-addons/package.json
* only cookie values for a single user are stored
* tenant context is not used anymore for entries to remain in the cookie
* set version to 9.1.1
=> Adapt history service

package-lock.json, package.json, src/clr-addons/components.clr-addons.scss, src/clr-addons/package.json, src/clr-addons/themes/phs/css.overrides.scss, src/dev/src/app/app.component.html, src/dev/src/app/app.component.ts, src/dev/src/app/date-time-container/date-time-container.demo.html, src/dev/src/app/date-time-container/date-time-container.demo.ts
+ Color of icons in header were no longer in theme color
+ Caret-Down-Icon misplaced and wrong size when used in header
Fix combobox issues:
+ Multiselect combobox extended across the page because of whitespace: nowrap
+ Remove the 100% width of combobox to avoid validation icon being displayed in next line
=> Fix styling bugs that occurred during clarity upgrade

src/clr-addons/history/history.service.ts, src/clr-addons/history/history.spec.ts
breadcrumbs (history) has a problem on stringify non-ascii UTF-8 characters in the url.
uriEncode the value first solves the issue (and uriDecode on loading)
=> fix: breadcrumbs/history encode/decode fixing

package-lock.json, package.json, src/clr-addons/numericfield/numeric-field.spec.ts, src/clr-addons/numericfield/numeric-field.ts
In case of input = 4.1 in the roundOrTruncate function "value * Math.pow(10, 2)" produces 409.99999999999994.
Same for 5.1 input.
=> Fixing rounding problem for NumericField in case of 4.1 or 5.1 input

package-lock.json, package.json, src/clr-addons/brand-avatar/brand-avatar.spec.ts, src/clr-addons/multilingual/abstract-multilingual.ts, src/clr-addons/multilingual/multilingual-input/multilingual-input.html, src/clr-addons/multilingual/multilingual-input/multilingual-input.spec.ts, src/clr-addons/multilingual/multilingual-textarea/multilingual-textarea.html, src/clr-addons/multilingual/multilingual-textarea/multilingual-textarea.spec.ts, src/clr-addons/package.json, src/dev/src/app/multilingual-input/multilingual-input.demo.html, src/dev/src/app/multilingual-input/multilingual-input.demo.ts
- New input clrLanguages: Defines which languages to show, regardless of bound form model
- New input clrMissingPrefix: Prefix which will be shown, when a text in a language is misisng
- New input clrFallbackLang: Language to show text from, when a text in a language is missing
=> Enhance multilang input/textarea

package.json, src/clr-addons/icons/shapes.ts, src/clr-addons/package.json
An icon with the name dollar-bill already exists in Clarity. This leads
to a name collision, possibly resulting in the wrong icon to be
displayed.
=> Rename icon due to name collision with Clarity

src/clr-addons/clr-addons.module.ts, src/clr-addons/components.clr-addons.scss, src/clr-addons/datagrid/date-filter/date-filter.component.html, src/clr-addons/datagrid/date-filter/date-filter.component.spec.ts, src/clr-addons/datagrid/date-filter/date-filter.component.ts, src/clr-addons/datagrid/date-filter/date-filter.module.ts, src/clr-addons/datagrid/date-filter/index.ts, src/clr-addons/datagrid/date-filter/nested-property.ts, src/clr-addons/datagrid/index.ts, src/dev/src/app/app.routing.ts, src/dev/src/app/datagrid-filters/clr-datagrid-filters-demo.html, src/dev/src/app/datagrid-filters/datagrid-filters.demo.module.ts, src/dev/src/app/datagrid-filters/datagrid-filters.demo.ts
This adds a date filter which can be used in any Clarity datagrid.
Closes #1759
=> feat: add a date filter for datagrid

package-lock.json, package.json, src/clr-addons/datagrid/date-filter/date-filter.component.ts, src/clr-addons/package.json
This fixes focusing on the date picker will hide the filter popup.
Closes #1862
=> fix: datagrid date filter popup handling

src/clr-addons/searchfield/search-field.spec.ts, src/clr-addons/searchfield/search-field.ts
Fix optional ngControl. 
Fixes #1906
Added unit-tests ✅
Also fixed the deprecated `initEvent` when creating input event in tests.
It's a little easier to review without white-space changes: https://github.com/porscheinformatik/clarity-addons/pull/1907/files?w=1
=> Fix optional ngControl. Fixes #1906

package-lock.json, package.json, src/clr-addons/dropdown/clr-dropdown-overflow.directive.ts, src/clr-addons/package.json, src/dev/src/app/location-bar/location-bar.demo.html, src/dev/src/app/location-bar/location-bar.demo.ts
Clarity sets the dropdown anchor to `position: static` after dropdown is opened once, which means if we open the dropdown a second time, the next `position: relative` parent will be different. This is also a problem because the calculation when using `AfterContentChecked` considers the element to be at "y" of the anchor, not the actual "y" coordinate.
~To be merged after #1973~
=> Fix dropdown overflow using wrong y position in the calculation

src/clr-addons/datagrid/enum-filter/enum-filter.component.html, src/clr-addons/datagrid/enum-filter/enum-filter.component.spec.ts, src/clr-addons/datagrid/enum-filter/enum-filter.component.ts, src/dev/src/app/enum-filter/enum-filter.demo.html, src/dev/src/app/enum-filter/enum-filter.demo.ts, website/src/app/documentation/demos/datagrid/datagrid.demo.html, website/src/app/documentation/demos/datagrid/datagrid.demo.ts
We would like to define a "display name" for enums in the `enum-filter` component. The reason is that the name of an enum in the code is often not user friendly. Also, for i18n purposes such a functionality is very useful for us.
Therefore, we extended the `clrPossibleValues` to either accept a list of strings (current master behaviour) or a list of `{ value: string, displayValue: string }` objects.
The demo project was extended to showcase our change:
**Current behaviour**
Enum values are shown as they are defined in code - not very user friendly
**Extension to specify a display name**
=> Datagrid enum filter: Add custom display name

src/clr-addons/datagrid/enum-filter/enum-filter.component.ts
Applying a persisted filter value was not working if custom display values were used.
Now, we filter the `clrFilterValues` against the `clrPossibleValues` via their `value` property.
=> Datagrid enum filter: Fix persistance

src/clr-addons/datagrid/datagrid-state-persistence/column-hidden-state-persistence.directive.ts, src/clr-addons/datagrid/datagrid-state-persistence/column-hidden-state-persistence.spec.ts, src/clr-addons/datagrid/datagrid-state-persistence/datagrid-field.directive.ts, src/dev/src/app/datagrid-state-persistence/datagrid-state-persistence.demo.html, src/dev/src/app/datagrid-state-persistence/datagrid-state-persistence.demo.ts, website/src/app/documentation/demos/datagrid/datagrid.demo.html
Until now, `clrDgField` directive was needed to persist the hidden-state of a column. We would like to extend persisting the hidden-state by defining a persistance key in the directive. This way, one can persist the hidden-state of a column without the need to set `clrDgField`. So `clrDgField` still remains the main source for the persistance key and fallbacks to the implemented extension.
Background is, that we have a couple of columns with calculated values and a server-driven datasource, therefore filtering is not possible on those columns. Still, we want to persist the hidden-state here.
I tried out different approaches and prefered the presented one here as it is slim and non-inversive (as the existing `clrDgHideableColumn` input is simply extended by another property), but I'm open …
=> Persist hidden state independently

src/clr-addons/components.clr-addons.scss
- Set text color of clr-control-helper when used in combination with *clrIfWarning
- Positioning of warning icon changed.
(cherry picked from commit 3a9426ea75ab3f208757eb671a34fc5f1f57e326)
=> Update clr-warning styles

website/angular.json, website/src/app/app.component.ts, website/src/app/documentation/get-started/get-started.component.html, website/src/app/utils/code-snippet.ts, website/src/index.html, website/src/styles/code.scss, website/src/styles/components.scss, website/src/styles/global.scss
this is just the website part of #2256, to change the rows etc I'll make a follow-up, as we'll need a version increase (and the status row classes are also broken in dark mode)
---
snippets before
snippets after
=> Style prism snippets based on selected theme

src/clr-addons/components.clr-addons.scss, website/src/app/documentation/demos/datagrid/datagrid.demo.html
Because of the dg row highlighting the background-color was set to `inherit`. But that leads to seeing the row content through the sticky row if there is no highlighting applied. This fix should reset the background-color only for the highlighted rows.
PS: REQ is not even ordered yet, will release this when needed.
before:
after:
=> Fix datagrid sticky row transparent background

package-lock.json, package.json, replace-versions.js, src/clr-addons/package.json, website/package-lock.json
+ update replace-versions.js script to do it automatically for Clarity versions too (not just Angular)
+ bump version to 18.1.6
=> Make Clarity dependencies more relaxed

src/clr-addons/history/history.service.ts
[C3DEV-317064](C3DEV-319667) Not more than 2 history entries are shown in Service (Es werden nicht mehr als 2 Historieneinträge im Service angezeigt) - C3REQPHSRE-4604
This reduces the Cookie length by about 33.25% on average and thus leads to the case with only 2 entries being shown happening less frequently.
Similiar Change will be contributed to cross-core-tapestry on gitlab too.
=> [C3DEV-317064](C3DEV-319667) Not more than 2 history entries are shown in Service

src/clr-addons/history/history.service.ts
Due to the previous changes a test with characters outside the latin 1 range fails and thus the commit has to be reverted.
=> revert of [C3DEV-317064](C3DEV-319667)

src/clr-addons/themes/phs/_css.overrides.scss, src/dev/src/app/readonly/readonly.demo.html, src/dev/src/app/readonly/readonly.demo.ts
The selected items wrapper and the text input of the combobox are by default displayed as two columns side by side. This looks really weird when the items are long. With the new `clr-combobox-vertical` class they are displayed on top of one another.
default styling
with optional class
=> Add "clr-combobox-vertical" CSS class for comboboxes with long items

package-lock.json, package.json, src/clr-addons/datagrid/datagrid-state-persistence/state-persistence-key.directive.ts, src/clr-addons/datagrid/datagrid-state-persistence/state-persistence-key.spec.ts, src/clr-addons/package.json, website/package-lock.json
(cherry picked from commit 37767847b2c7f57406856be212cbc2bcd0dd8632)
=> Fix a case where persisted filters don't apply when the "property" field is an input signal (backport to v18)
