porscheinformatik/clarity-addons

src/clr-addons/collapse-expand-section/collapse-expand-section.module.ts

only allowed to be imported once in the app module

Remove browser animation module import

---

.gitignore
src/clr-addons/paged-search-result-list/paged-search-result-list.html
src/clr-addons/paged-search-result-list/paged-search-result-list.scss
src/clr-addons/pager/pager.html
src/clr-addons/pager/pager.scss
src/clr-addons/pager/pager.ts

remove clr prefix from css class names

Pager: mark not clickable buttons as disabled

---

src/clr-addons/content-panel/content-panel.scss
src/clr-addons/content-panel/content-panel.ts

fix build by making variable not private

Hide scrollbars in clr-content-panel-container

---

latest/src/app/documentation/demos/full-page-layouts/basepage-layout/basepage-layout.demo.html
latest/src/app/documentation/demos/generic-pager/generic-pager.demo.html

Adapt content panel layout demo

Move input fields of pager demo into form

---

src/clr-addons/components.clr-addons.scss
src/clr-addons/themes/mvap/css.overrides.scss
src/clr-addons/themes/mvap/theme.mvap.clarity.scss
src/clr-addons/themes/vu3/css.overrides.scss
src/clr-addons/themes/vu3/theme.vu3.clarity.scss
src/dev/src/app/app.module.ts
src/dev/src/app/app.routing.ts
src/dev/src/app/cards/cards.demo.html
src/dev/src/app/cards/cards.demo.module.ts
src/dev/src/app/cards/cards.demo.ts

Add card-active class for VU3 and mVAP

---

src/clr-addons/components.clr-addons.scss
src/clr-addons/flow-bar/flow-bar.ts
src/clr-addons/themes/vu3/css.overrides.scss
src/dev/src/app/cards/cards.demo.html
src/dev/src/app/flow-bar-content-panel/flow-bar-content-panel.demo.html
src/dev/src/app/flow-bar/flow-bar.demo.html
src/dev/src/app/flow-bar/flow-bar.demo.ts

- Adapt dev demos
- Create exclusive selectable card style, different from default clickable

Add substeps to flow component

---

latest/package.json
latest/src/app/documentation/demos/cards/cards.demo.html
latest/src/app/documentation/demos/flow-bar-layout/flow-bar-layout.demo.html
latest/src/app/documentation/demos/flow-bar-layout/flow-bar-layout.demo.ts
latest/src/app/documentation/demos/full-page-layouts/demo-menu/demo-menu.html
latest/src/app/documentation/demos/full-page-layouts/flow-bar-layout/flow-bar-layout.demo.html
latest/src/app/documentation/demos/full-page-layouts/flow-bar-layout/flow-bar-layout.demo.ts
latest/src/app/documentation/demos/full-page-layouts/full-page-layouts-routing.module.ts
latest/src/app/documentation/demos/full-page-layouts/sticky-footer-layout/sticky-footer-layout.demo.html
latest/src/app/documentation/demos/full-page-layouts/sticky-footer-layout/sticky-footer-layout.demo.module.ts
latest/src/app/documentation/demos/full-page-layouts/sticky-footer-layout/sticky-footer-layout.demo.ts
latest/src/app/documentation/demos/paged-search-result-list/paged-search-result-list.demo.html
latest/src/app/documentation/demos/sticky-footer-layout/sticky-footer-layout.demo.html
latest/src/app/documentation/demos/sticky-footer-layout/sticky-footer-layout.demo.module.ts
latest/src/app/documentation/demos/sticky-footer-layout/sticky-footer-layout.demo.ts
latest/src/app/documentation/documentation-routing.module.ts
latest/src/settings/componentlist.json

- update clr addons demo to go through subflow steps

Add demo for sticky footer without flow bar

---

src/clr-addons/themes/vu3/theme.vu3.clarity.scss

made radio button selection ring thinner to match VU3 mockups

made radio button selection ring thinner

---

src/clr-addons/themes/vu3/css.overrides.scss

- increased button border radius
- made form labels slightly thinner

implement some VU3 mockup features

---

package.json
src/clr-addons/treetable/renderer/main-renderer.ts

-apply changes on window resized.
-add timeout to make sure the view is finalised.

TreeTable : support ChangeDetection onPush.

---

package.json
src/clr-addons/content-panel/content-panel.html
src/clr-addons/content-panel/content-panel.ts
src/clr-addons/package.json

- increase timeout for window resize event when closing the panel

contentPanel : increase timeout for window resize

---

package.json
src/clr-addons/date-time-container/index.ts
src/clr-addons/index.ts
src/clr-addons/package.json

Add index ts file for date-time-container

---

package.json
src/clr-addons/package.json

reason: wrong build published for 5.1.2

Release version 5.1.3

---

src/clr-addons/numericfield/numeric-field.spec.ts
src/clr-addons/numericfield/numeric-field.ts
src/dev/src/app/numericfield/numericfield.demo.html
src/dev/src/app/numericfield/numericfield.demo.ts

implement rounding + fix several issues

 Update numeric-field.ts

---

package.json

Increased version number to get a new release including the #381 fix

Update version to 5.1.13

---

src/clr-addons/numericfield/numeric-field.spec.ts
src/clr-addons/numericfield/numeric-field.ts

finalFormatting was not executed on iPad

(165366) change finalFormatting to on blur

---

src/clr-addons/flow-bar/flow-bar.scss

- adding box-shadow and removig outline

Fix the focus for flow-bar

---

src/clr-addons/combobox/combobox.ts
src/clr-addons/combobox/option.ts
src/clr-addons/combobox/providers/option-selection.service.ts
src/dev/src/app/combobox/combobox.demo.html
src/dev/src/app/combobox/combobox.demo.ts

+ preselected option gets selected when options change
+ enter reopened combobox, as the search got triggered
+ ExpressionChangedAfterItHasBeenCheckedError for selected option

Fix combobox

---

package-lock.json
package.json
src/clr-addons/combobox/combobox.ts
src/clr-addons/combobox/option.ts
src/clr-addons/combobox/providers/option-selection.service.ts
src/clr-addons/package.json
src/dev/src/app/combobox/combobox.demo.html
src/dev/src/app/combobox/combobox.demo.ts

+ preselected option gets selected when options change
+ enter reopened combobox, as the search got triggered
+ ExpressionChangedAfterItHasBeenCheckedError for selected option

Fix combobox (#513)

---

npm/clr-addons/package.json
package-lock.json
package.json
src/clr-addons/clr-addons.module.ts
src/clr-addons/components.clr-addons.scss
src/clr-addons/generic-quick-list/generic-quick-list.html
src/clr-addons/generic-quick-list/generic-quick-list.module.ts
src/clr-addons/generic-quick-list/generic-quick-list.scss
src/clr-addons/generic-quick-list/generic-quick-list.spec.ts
src/clr-addons/generic-quick-list/generic-quick-list.ts
src/clr-addons/generic-quick-list/index.ts
src/clr-addons/index.ts
src/clr-addons/letter-avatar/index.ts
src/clr-addons/package.json
src/clr-addons/quick-list/quick-list.scss
src/dev/src/app/app.module.ts
src/dev/src/app/app.routing.ts
src/dev/src/app/generic-quick-list/generic-quick-list.demo.html
src/dev/src/app/generic-quick-list/generic-quick-list.demo.module.ts
src/dev/src/app/generic-quick-list/generic-quick-list.demo.ts
src/dev/src/app/multilingual-input/multilingual-input.demo.ts
src/dev/src/app/progress-spinner/progress-spinner.demo.module.ts

+ Additionally update clarity to 2.2.0

New component: Generic Quick List

---

src/clr-addons/components.clr-addons.scss
src/clr-addons/components.variables.clr-addons.scss
src/clr-addons/header.clr-addons.scss
src/clr-addons/mobile.scss

Especially fix issues which only occur on safari

Change layout to support scrolling & sticky footer on smartphones

---

package-lock.json
package.json
src/clr-addons/components.clr-addons.scss
src/clr-addons/package.json

Release new version 6.4.3

---

package-lock.json
package.json
src/clr-addons/package.json
src/clr-addons/view-edit-section/view-edit-section.scss

[View Edit Section] Make card-block a flex-container inside the VES

---

latest/package-lock.json
latest/package.json
latest/src/app/documentation/demos/full-page-layouts/view-edit-section-layout/view-edit-section-layout.demo.html
latest/src/app/documentation/demos/full-page-layouts/view-edit-section-layout/view-edit-section-layout.ts

Adapt full page layout demo of View Edit Section

---

package-lock.json
package.json
src/clr-addons/combobox/_combobox.clarity.scss
src/clr-addons/combobox/combobox.html
src/clr-addons/combobox/combobox.spec.ts
src/clr-addons/combobox/combobox.ts
src/clr-addons/package.json
src/dev/src/app/combobox/combobox.demo.html
src/dev/src/app/combobox/combobox.demo.ts

A small change allowing us to disable a combobox and also use *clrIfError on control errors in the combobox.

Add disabled state & if error directive to combobox

---

src/clr-addons/treetable/treetable.scss
src/dev/src/app/treetable/treetable.demo.html

* Add fixed height demo
closes #838

Fix treetable header expand button drops through

---

src/clr-addons/multilingual/multilingual-textarea/multilingual-textarea.html
src/clr-addons/multilingual/multilingual.scss

* use clr-textarea-wrapper for textares
* add margin to selector to get rid of it when hidden

Fix layout for multilingual input/textarea

---

package-lock.json
package.json
src/clr-addons/history/history.service.ts
src/clr-addons/package.json

* increment version 8.3.0 -> 8.3.1

[192374] fix angular history service

---

package-lock.json
package.json
src/clr-addons/autocomplete-off/autocomplete-off.directive.ts
src/clr-addons/autocomplete-off/autocomplete-off.module.ts
src/clr-addons/autocomplete-off/autocomplete-off.spec.ts
src/clr-addons/clr-addons.module.ts

This directive turns off autocomplete in inputs by default

New directive: AutocompleteOff

---

package-lock.json
package.json
src/clr-addons/abstract-form-component/abstract-form-component.spec.ts
src/clr-addons/abstract-form-component/abstract-form-component.ts
src/clr-addons/multilingual/multilingual-input/multilingual-input.spec.ts
src/clr-addons/multilingual/multilingual-input/multilingual-input.ts
src/clr-addons/multilingual/multilingual-textarea/multilingual-textarea.spec.ts
src/clr-addons/multilingual/multilingual-textarea/multilingual-textarea.ts
src/clr-addons/numericfield/numeric-field.spec.ts
src/clr-addons/numericfield/numeric-field.ts
src/clr-addons/package.json

Fix validation handling on paste on numeric field

---

karma.conf.js
package-lock.json
package.json
src/clr-addons/package.json
src/clr-addons/quick-list/add-option.html
src/clr-addons/quick-list/quick-list.html

node-sass was already replaced by sass long time ago

Remove node-sass and fix quick-list buttons

---

package-lock.json
package.json
src/clr-addons/multilingual/index.ts
src/clr-addons/multilingual/multilingual.module.ts
src/clr-addons/package.json

This change exports the ClrMultilingualSelector and exposes it in the public API.

Expose multilingual selector

---

latest/package-lock.json
latest/package.json
latest/src/app/documentation/demos/brand-avatar/brand-avatar.demo.html
latest/src/app/documentation/demos/brand-avatar/brand-avatar.demo.module.ts
latest/src/app/documentation/demos/brand-avatar/brand-avatar.demo.scss
latest/src/app/documentation/demos/brand-avatar/brand-avatar.demo.ts
latest/src/app/documentation/documentation-routing.module.ts
latest/src/settings/componentlist.json

- added demo page for new brand avatar
- increased clarity addons version (to include brand avatar)

#1184 brand avatar demo page

---

package-lock.json
package.json
src/clr-addons/numericfield/numeric-field.spec.ts
src/clr-addons/numericfield/numeric-field.ts

NumericField: Fix calculation

---

package-lock.json
package.json
src/clr-addons/components.clr-addons.scss
src/clr-addons/header.clr-addons.scss
src/clr-addons/mobile.scss
src/clr-addons/package.json
src/dev/src/app/kitchen-sink/kitchen-sink.html

Fixes password width changing on focus
Fixes #969

Some fixes

---

package-lock.json
package.json
src/clr-addons/view-edit-section/view-edit-section.html
src/clr-addons/view-edit-section/view-edit-section.scss
src/clr-addons/view-edit-section/view-edit-section.spec.ts
src/clr-addons/view-edit-section/view-edit-section.ts

Introduces the collapse/expand feature to the View/Edit-Section.

Make view/edit section collapsable

---

package-lock.json
package.json
src/clr-addons/view-edit-section/view-edit-section.html
src/clr-addons/view-edit-section/view-edit-section.scss
src/clr-addons/view-edit-section/view-edit-section.spec.ts
src/clr-addons/view-edit-section/view-edit-section.ts

(cherry picked from commit d40f8ee418926b1a145505aef0fa9dd05d566067)

Make view/edit section collapsible

---

package-lock.json
package.json
src/clr-addons/package.json

https://github.com/sindresorhus/cpy-cli/issues/35

Downgrade dependency cpy-cli due to a bug

---

package.json
src/clr-addons/flow-bar/flow-bar.module.ts
src/clr-addons/history/history.module.ts
src/clr-addons/location-bar/location-bar.module.ts
src/clr-addons/multilingual/multilingual.module.ts
src/clr-addons/package.json

because they are encapsulated when imported, we need to add the import to the modules itself

add import of dropdownoverflow for modules which implement dropdowns

---

package-lock.json
package.json
src/clr-addons/multilingual/abstract-multilingual.ts
src/clr-addons/package.json
src/dev/src/app/multilingual-input/multilingual-input.demo.html
src/dev/src/app/multilingual-input/multilingual-input.demo.ts

- Only set fallback text if there is any
- Dont apply fallback text to currently editing language

Multilang: Fix missing prefix handling

---

package-lock.json
package.json
src/clr-addons/components.clr-addons.scss
src/clr-addons/package.json
src/dev/src/app/datagrid-state-persistence/datagrid-state-persistence.demo.html
website/.angular.json
website/package-lock.json
website/src/app/app.module.ts
website/src/app/documentation/demos/datagrid/datagrid.demo.html
website/src/app/documentation/demos/datagrid/datagrid.demo.ts
website/src/app/utils/code-highlight.ts

Also fixed prismjs usage in website

Datagrid: CSS for maximum height

---

package.json
src/clr-addons/icons/shapes.ts

ADD ICONS - campaign and campaignOutdated

---

package-lock.json
package.json
src/clr-addons/package.json

Fix TypeError: Cannot read properties of null (reading clientHeight) for v12

---

src/clr-addons/header.clr-addons.scss
src/dev/src/app/content-container.component.ts
website/src/app/documentation/demos/full-page-layouts/sidebarpage-layout/sidebarpage-layout.demo.html
website/src/app/documentation/demos/page-layouts/page-layouts.demo.html
website/src/app/documentation/documentation-nav-links.component.ts
website/src/app/documentation/documentation.component.html
website/src/app/icons/icons.component.html
website/src/styles/global.scss

Replace sidenav with vertical-nav for demo pages

---

website/src/app/documentation/internationalization/internationalization.component.ts

Added locales fr and nl
Added locales de-BE, en-BE, fr-BE, nl-BE
Renamed localeEnUS to localeEn as it imports only 'en'

Add BE locales to Internationalization page

---

website/src/app/documentation/internationalization/internationalization.component.ts

Added locales en-SE, pt-PT, se-SE
Note: there's no en-PT available in Angular - see https://www.npmjs.com/package/@angular/common?activeTab=code

Add PT and SE locales to Internationalization page

---

package-lock.json
package.json
src/clr-addons/datagrid/datagrid-state-persistence/column-hidden-state-persistence.directive.ts
src/clr-addons/datagrid/datagrid-state-persistence/column-hidden-state-persistence.spec.ts
src/clr-addons/datagrid/datagrid-state-persistence/datagrid-state-persistence-model.interface.ts
src/clr-addons/datagrid/datagrid-state-persistence/index.ts
src/clr-addons/datagrid/datagrid-state-persistence/state-persistence-key.directive.ts
src/clr-addons/datagrid/datagrid-state-persistence/state-persistence-key.spec.ts
src/clr-addons/datagrid/datagrid-state-persistence/state-persistence-options.interface.ts
src/clr-addons/package.json
website/src/app/documentation/demos/datagrid/datagrid.demo.html

No version increase yet because I have a few more PRs coming for other previously discussed persistence improvements but splitting by topic makes it easier to read and review

Add persistence for sort column and sort order

---

src/clr-addons/dropdown/clr-dropdown-overflow.directive.ts

- fix styles not being applied after a nested dropdown is displayed and hidden again
- fix multiple subscriptions to ContentChildren changes

Fixes for asynchronously resolved nested dropdowns

---

src/clr-addons/mobile.scss

just something small I noticed, no ticket so no version needed

Fix padding for .content-header on mobile devices

---

src/clr-addons/clr-addons.module.ts
src/clr-addons/clr-control-warning/if-warning.directive.ts
src/clr-addons/clr-control-warning/if-warning.module.ts
src/clr-addons/clr-control-warning/index.ts
src/clr-addons/components.clr-addons.scss
src/clr-addons/index.ts
src/dev/src/app/app.routing.ts
website/src/app/documentation/demos/control-warning/control-warning.demo.html
website/src/app/documentation/demos/control-warning/control-warning.demo.module.ts
website/src/app/documentation/demos/control-warning/control-warning.demo.spec.ts
website/src/app/documentation/demos/control-warning/control-warning.demo.ts
website/src/app/documentation/documentation-routing.module.ts

(cherry picked from commit 39a636e123dcd96cbcd2f9f79493f98aea7d361a)

if-warning Directive for clr-helper-components (#2176)

---

src/clr-addons/components.clr-addons.scss

(cherry picked from commit 05a3976be70fd0760827b907fe03addf0d866a51)

Updated clr-warning color for form controls (#2186)

---

src/clr-addons/components.clr-addons.scss

- Set text color of clr-control-helper when used in combination with *clrIfWarning
- Positioning of warning icon changed.

Update clr-warning styles

---

package-lock.json
package.json
src/clr-addons/package.json
website/package-lock.json
website/src/app/icons/icons-get-started/icons-get-started.component.html
website/src/app/icons/icons-get-started/icons-get-started.component.ts

+ add "allIcons" to documentation

Version 17.3.1

---

package-lock.json
package.json
src/clr-addons/flow-bar/flow-bar.scss
src/clr-addons/package.json
website/package-lock.json
website/src/app/documentation/demos/full-page-layouts/flow-bar-layout/flow-bar-layout.demo.ts

Fix flow-bar color for disabled steps

---

website/src/app/documentation/get-started/get-started.component.html
website/src/app/documentation/get-started/get-started.component.ts

+ Update link to POI internal contribution guidelines (page has changed)

Update docs for enabling PHS theme - add to body instead of html tag

---

src/clr-addons/history/history-pinned.ts
src/clr-addons/history/history.provider.ts
src/clr-addons/history/history.ts
src/clr-addons/history/index.ts

- added interface to modify history elements in history element and pinned history

Added history provider interface

---

src/clr-addons/history/history-model.interface.ts

Fix index type of the history model context (allow undefined values)

---

src/clr-addons/datagrid/datagrid-state-persistence/state-persistence-key.spec.ts

Use different keys for each test (because of LocalStorage)

Fix StatePersistenceKeyDirective tests influencing each other

---

src/clr-addons/treetable/treetable.scss
src/dev/src/app/treetable/treetable.demo.html

Support more treetable levels

---

package-lock.json
package.json
src/clr-addons/package.json
src/clr-addons/themes/phs/_css.overrides.scss
src/dev/src/app/app.routing.ts
src/dev/src/app/combobox/combobox.demo.html
src/dev/src/app/combobox/combobox.demo.ts
website/package-lock.json

caused by 29bddf43
explained in the CSS comment

Fix default multi-selection combobox text input wrong width

---

src/clr-addons/collapse-expand-section/collapse-expand-section.html
src/clr-addons/collapse-expand-section/collapse-expand-section.ts
src/dev/src/app/collapse-expand-section/collapse-expand-section.demo.html

Fix collapse-expand-section animation playing when already expanded at initialization

---

package-lock.json
package.json
src/clr-addons/main-nav-group/main-nav-group.html
src/clr-addons/main-nav-group/main-nav-group.scss
src/clr-addons/main-nav-group/main-nav-group.ts
src/clr-addons/package.json
src/dev/src/app/app.component.html
src/dev/src/app/app.component.ts
website/package-lock.json
website/src/app/documentation/demos/full-page-layouts/demo-menu/demo-menu.html
website/src/app/documentation/demos/full-page-layouts/demo-menu/demo-menu.ts

via input `clrIcon` for the shape
without icon
with icon
Resolves #2541

Add the possibility to show icons in MainNavGroup

---

package-lock.json
package.json
src/clr-addons/components.clr-addons.scss
src/clr-addons/package.json
src/dev/src/app/readonly/readonly.demo.html
website/package-lock.json
website/src/app/documentation/demos/readonly/readonly.demo.html
website/src/app/documentation/demos/readonly/readonly.demo.ts

tldr - extending the radio/checkbox readonly styling to the toggles too + a few small adaptations for styling consistency as toggles are not 100% the same as radios/checkboxes

Add toggle support to the readonly directive

---

package-lock.json
package.json
src/clr-addons/components.clr-addons.scss
src/clr-addons/package.json
website/package-lock.json

Remove margin-top from textareas to align them with labels

---

src/clr-addons/brand-avatar/brand-avatar.ts

- added a case for 'VW PKW' to default do 'VW'

[C3DEV-450781] [UI/UX] Brand logos for vehicles missing in various service pages

---

package-lock.json
package.json
src/clr-addons/history/history-model.interface.ts
src/clr-addons/history/history-pinned.html
src/clr-addons/history/history-pinned.ts
src/clr-addons/history/history.html
src/clr-addons/history/history.http.impl.service.ts
src/clr-addons/history/history.http.service.ts
src/clr-addons/history/history.module.ts
src/clr-addons/history/history.service.ts
src/clr-addons/history/history.spec.ts
src/clr-addons/history/history.ts
src/clr-addons/history/index.ts
src/clr-addons/package.json
src/dev/src/app/_mocks/history.http.mock.service.ts
src/dev/src/app/app.component.html
src/dev/src/app/app.module.ts
src/dev/src/app/route-history.service.ts
website/package-lock.json
website/package.json
website/src/app/documentation/demos/full-page-layouts/basepage-layout/basepage-layout.demo.html
website/src/app/documentation/demos/full-page-layouts/basepage-layout/basepage-layout.ts
website/src/app/documentation/demos/history/_mocks/history.http.mock.service.ts
website/src/app/documentation/demos/history/history.demo.html
website/src/app/documentation/demos/history/history.demo.module.ts
website/src/app/documentation/demos/history/history.demo.ts

As cookies get too big and are sent for every request, it was decided to move the storage to backend

History: Change behaviour to use a backend service for storing entries

---

package-lock.json
package.json
src/clr-addons/clr-addons.module.ts
src/clr-addons/export-datagrid-button/export-datagrid.service.ts
src/clr-addons/package.json
src/dev/src/app/exportable-datagrid/exportable-datagrid.module.ts
website/package-lock.json
website/src/app/documentation/demos/datagrid/datagrid.demo.module.ts

Make zipcelx optional
